# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('qtr', models.IntegerField()),
                ('crsabbr', models.CharField(max_length=10)),
                ('crsno', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('enroll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.IntegerField()),
                ('tran_yr', models.IntegerField()),
                ('tran_qtr', models.IntegerField()),
                ('dept_abbrev', models.CharField(max_length=20)),
                ('course_number', models.IntegerField()),
                ('section_id', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=6)),
            ],
        ),
    ]
